export const federalCases = [
  { "id": "USSC", "value": "U.S. Supreme Court" },
  { "id": "1stCir", "value": "1st Circuit" },
  { "id": "2ndCir", "value": "2nd Circuit" },
  { "id": "3rdCir", "value": "3rd Circuit" },
  { "id": "4thCir", "value": "4th Circuit" },
  { "id": "5thCir", "value": "5th Circuit" },
  { "id": "6thCir", "value": "6st Circuit" },
  { "id": "7thCir", "value": "7th Circuit" },
  { "id": "8thCir", "value": "8rd Circuit" },
  { "id": "9thCir", "value": "9th Circuit" },
  { "id": "10thCir", "value": "10th Circuit" },
  { "id": "DCCir", "value": "DC Circuit" },
  { "id": "FedCir", "value": "Federal Circuit" },
  { "id": "TaxCt", "value": "Tax Court" },
  { "id": "AdminMat", "value": "Administrative Materials" },
  { "id": "FedReg", "value": "Federal Register" },
]

export const federalSR = [
  { "id": "USC", "value": "U.S. Code" },
  { "id": "CFR", "value": "Code of Federal Regulations" },
  { "id": "USCN", "value": "U.S. Constitution" },
]

export const federalSRR = [
  { "id": "SR", "value": "Statues and Regulations" },
  { "id": "Rule", "value": "Rule" },
]

export const federalRule = [
  { "id": "FRCP", "value": "Federal Rules of Civil Procedure" },
  { "id": "FRAP", "value": "Federal Rules of Appellate Procedure" },
  { "id": "FRE", "value": "Federal Rules of Evidence" },
  { "id": "FRCLP", "value": "Federal Rules of Criminal Procedure" },
  { "id": "FRBP", "value": "Federal Rules of Bankruptcy Procedure" },
]

export const statesCases = [
  { id: "Alaska", value: "Alaska" },
  { id: "Alabama", value: "Alabama" },
  { id: "Arizona", value: "Arizona" },
  { id: "Arkansas", value: "Arkansas" },
  { id: "California", value: "California" },
  { id: "Colorado", value: "Colorado" },
  { id: "Connecticut", value: "Connecticut" },
  { id: "Delaware", value: "Delaware" },
  { id: "District of Columbia", value: "District of Columbia" },
  { id: "Florida", value: "Florida" },
  { id: "Georgia", value: "Georgia" },
  { id: "Guam", value: "Guam" },
  { id: "Hawaii", value: "Hawaii" },
  { id: "Idaho", value: "Idaho" },
  { id: "Illinois", value: "Illinois" },
  { id: "Indiana", value: "Indiana" },
  { id: "Iowa", value: "Iowa" },
  { id: "Kansas", value: "Kansas" },
  { id: "Kentucky", value: "Kentucky" },
  { id: "Louisiana", value: "Louisiana" },
  { id: "Maine", value: "Maine" },
  { id: "Maryland", value: "Maryland" },
  { id: "Massachusetts", value: "Massachusetts" },
  { id: "Michigan", value: "Michigan" },
  { id: "Minnesota", value: "Minnesota" },
  { id: "Mississippi", value: "Mississippi" },
  { id: "Missouri", value: "Missouri" },
  { id: "Montana", value: "Montana" },
  { id: "Nebraska", value: "Nebraska" },
  { id: "Nevada", value: "Nevada" },
  { id: "New Hampshire", value: "New Hampshire" },
  { id: "New Jersey", value: "New Jersey" },
  { id: "New Mexico", value: "New Mexico" },
  { id: "New York", value: "New York" },
  { id: "North Carolina", value: "North Carolina" },
  { id: "North Dakota", value: "North Dakota" },
  { id: "Northern Mariana Islands", value: "Northern Mariana Islands" },
  { id: "Ohio", value: "Ohio" },
  { id: "Oklahoma", value: "Oklahoma" },
  { id: "Oregon", value: "Oregon" },
  { id: "Pennsylvania", value: "Pennsylvania" },
  { id: "Puerto Rico", value: "Puerto Rico" },
  { id: "Rhode Island", value: "Rhode Island" },
  { id: "South Carolina", value: "South Carolina" },
  { id: "South Dakota", value: "South Dakota" },
  { id: "Tennessee", value: "Tennessee" },
  { id: "Texas", value: "Texas" },
  { id: "Utah", value: "Utah" },
  { id: "Vermont", value: "Vermont" },
  { id: "Virgin Islands", value: "Virgin Islands" },
  { id: "Virginia", value: "Virginia" },
  { id: "Washington", value: "Washington" },
  { id: "West Virginia", value: "West Virginia" },
  { id: "Wisconsin", value: "Wisconsin" },
  { id: "Wyoming", value: "Wyoming" }
];

export const allStatesCases = [
  { id: "Alaska", value: "Alaska" },
  { id: "Alabama", value: "Alabama" },
  { id: "Arizona", value: "Arizona" },
  { id: "Arkansas", value: "Arkansas" },
  { id: "California", value: "California" },
  { id: "Colorado", value: "Colorado" },
  { id: "Connecticut", value: "Connecticut" },
  { id: "Delaware", value: "Delaware" },
  { id: "District of Columbia", value: "District of Columbia" },
  { id: "Florida", value: "Florida" },
  { id: "Georgia", value: "Georgia" },
  { id: "Hawaii", value: "Hawaii" },
  { id: "Idaho", value: "Idaho" },
  { id: "Illinois", value: "Illinois" },
  { id: "Indiana", value: "Indiana" },
  { id: "Iowa", value: "Iowa" },
  { id: "Kansas", value: "Kansas" },
  { id: "Kentucky", value: "Kentucky" },
  { id: "Maine", value: "Maine" },
  { id: "Maryland", value: "Maryland" },
  { id: "Massachusetts", value: "Massachusetts" },
  { id: "Michigan", value: "Michigan" },
  { id: "Minnesota", value: "Minnesota" },
  { id: "Mississippi", value: "Mississippi" },
  { id: "Missouri", value: "Missouri" },
  { id: "Montana", value: "Montana" },
  { id: "Nebraska", value: "Nebraska" },
  { id: "Nevada", value: "Nevada" },
  { id: "New Hampshire", value: "New Hampshire" },
  { id: "New Jersey", value: "New Jersey" },
  { id: "New Mexico", value: "New Mexico" },
  { id: "New York", value: "New York" },
  { id: "North Carolina", value: "North Carolina" },
  { id: "North Dakota", value: "North Dakota" },
  { id: "Ohio", value: "Ohio" },
  { id: "Oklahoma", value: "Oklahoma" },
  { id: "Oregon", value: "Oregon" },
  { id: "Pennsylvania", value: "Pennsylvania" },
  { id: "Puerto Rico", value: "Puerto Rico" },
  { id: "Rhode Island", value: "Rhode Island" },
  { id: "South Carolina", value: "South Carolina" },
  { id: "South Dakota", value: "South Dakota" },
  { id: "Tennessee", value: "Tennessee" },
  { id: "Texas", value: "Texas" },
  { id: "Utah", value: "Utah" },
  { id: "Vermont", value: "Vermont" },
  { id: "Virginia", value: "Virginia" },
  { id: "Washington", value: "Washington" },
  { id: "West Virginia", value: "West Virginia" },
  { id: "Wisconsin", value: "Wisconsin" },
  { id: "Wyoming", value: "Wyoming" }
];

export const allStatesSRR = {
  "Alabama": [{ id: 'Alabama Code', value: 'Alabama Code' },
  { id: 'Alabama Administrative Code', value: 'Alabama Administrative Code' },
  { id: 'Alabama Code Rules', value: 'Alabama Code Rules' }],
  "Alaska": [{ id: 'Alaska Statutes', value: 'Alaska Statutes' },
  { id: 'Alaska Administrative Code', value: 'Alaska Administrative Code' },
  { id: 'Alaska Code Rules', value: 'Alaska Code Rules' }],
  "Arizona": [{ id: 'Arizona Revised Statutes', value: 'Arizona Revised Statutes' },
  { id: 'Arizona Administrative Code', value: 'Arizona Administrative Code' },
  { id: 'Arizona Code Rules', value: 'Arizona Code Rules' }],
  "Arkansas": [{ id: 'Arkansas Code', value: 'Arkansas Code' },
  { id: 'Arkansas Administrative Code', value: 'Arkansas Administrative Code' },
  { id: 'Arkansas Code Rules', value: 'Arkansas Code Rules' }],
  "California": [{ id: 'California Code', value: 'California Code' },
  { id: 'California Code of Regulations', value: 'California of Regulations' },
  { id: 'California Rules', value: 'California Rules' },
  { id: 'California Constitution', value: 'California Constitution' },],
  "Colorado": [{ id: 'Colorado Revised Statutes', value: 'Colorado Revised Statutes' },
  { id: 'Colorado Administrative Code', value: 'Colorado Administrative Code' },
  { id: 'Colorado Code Rules', value: 'Colorado Code Rules' }],
  "Connecticut": [{ id: 'Connecticut Statutes', value: 'Connecticut Code' },
  { id: 'Connecticut Administrative Code', value: 'Connecticut Administrative Code' },
  { id: 'Connecticut Code Rules', value: 'Connecticut Code Rules' }],
  "Delaware": [{ id: 'Delaware Code', value: 'Delaware Code' },
  { id: 'Delaware Administrative Code', value: 'Delaware Administrative Code' },
  { id: 'Delaware Code Rules', value: 'Delaware Code Rules' }],
  "District of Columbia": [{ id: 'District of Columbia Code', value: 'District of Columbia Code' },
  { id: 'District of Columbia Administrative Code', value: 'District of Columbia Administrative Code' },
  { id: 'District of Columbia Code Rules', value: 'District of Columbia Code Rules' }],
  "Florida": [{ id: 'Florida Statutes', value: 'Florida Code' },
  { id: 'Florida Administrative Code', value: 'Florida Administrative Code' },
  { id: 'Florida Code Rules', value: 'Florida Code Rules' }],
  "Georgia": [{ id: 'Georgia Code', value: 'Georgia Code' },
  { id: 'Georgia Compiled Rules & Regulations', value: 'Alabama Compiled Rules & Regulations' },
  { id: 'Georgia Code Rules', value: 'Georgia Code Rules' }],
  "Hawaii": [{ id: 'Hawaii Revised Statutes', value: 'Hawaii Revised Statutes' },
  { id: 'Hawaii Code of Rules', value: 'Hawaii Code of Rules' },
  { id: 'Hawaii Code Rules', value: 'Hawaii Code Rules' }],
  "Idaho": [{ id: 'Idaho Code', value: 'Idaho Code' },
  { id: 'Idaho Administrative Code', value: 'Idaho Administrative Code' },
  { id: 'Idaho Code Rules', value: 'Idaho Code Rules' }],
  "Illinois": [{ id: 'Illinois Compiled Statutes', value: 'Illinois Compiled Statutes' },
  { id: 'Illinois Administrative Code', value: 'Illinois Administrative Code' },
  { id: 'Illinois Code Rules', value: 'Illinois Code Rules' }],
  "Indiana": [{ id: 'Indiana Code', value: 'Indiana Code' },
  { id: 'Indiana Administrative Code', value: 'Indiana Administrative Code' },
  { id: 'Indiana Code Rules', value: 'Indiana Code Rules' }],
  "Iowa": [{ id: 'Iowa Code', value: 'Iowa Code' },
  { id: 'Iowa Administrative Code', value: 'Iowa Administrative Code' },
  { id: 'Iowa Code Rules', value: 'Iowa Code Rules' }],
  "Kansas": [{ id: 'Kansas Statutes', value: 'Kansas Statutes' },
  { id: 'Kansas Administrative Code', value: 'Kansas Administrative Code' },
  { id: 'Kansas Code Rules', value: 'Kansas Code Rules' }],
  "Kentucky": [{ id: 'Kentucky Revised Statutes', value: 'Kentucky Revised Statutes' },
  { id: 'Kentucky Administrative Code', value: 'Kentucky Administrative Code' },
  { id: 'Kentucky Code Rules', value: 'Kentucky Code Rules' }],
  "Maine": [{ id: 'Maine Statutes', value: 'Maine Statutes' },
  { id: 'Maine Code of Rules', value: 'Maine Code of Rules' },
  { id: 'Maine Code Rules', value: 'Maine Code Rules' }],
  "Maryland": [{ id: 'Code of Maryland', value: 'Code of Maryland' },
  { id: 'Maryland Code of Regulations', value: 'Maryland Code of Regulations' },
  { id: 'Maryland Code Rules', value: 'Maryland Code Rules' }],
  "Massachusetts": [{ id: 'General Law of Massachusetts', value: 'General Law of Massachusetts' },
  { id: 'Massachusetts Regulations', value: 'Massachusetts Regulations' },
  { id: 'Alabama Code Rules', value: 'Alabama Code Rules' }],
  "Michigan": [{ id: 'Michigan Compiled Law', value: 'Michigan Compiled Law' },
  { id: 'Michigan Compiled Law Administrative Code', value: 'Michigan Compiled Law Administrative Code' },
  { id: 'Michigan Compiled Law Code Rules', value: 'Michigan Compiled Law Code Rules' }],
  "Minnesota": [{ id: 'Minnesota Statutes', value: 'Minnesota Statutes' },
  { id: 'Minnesota Administrative Rules', value: 'Minnesota Administrative Rules' },
  { id: 'Minnesota Code Rules', value: 'Minnesota Code Rules' }],
  "Mississippi": [{ id: 'Mississippi Code', value: 'Mississippi Code' },
  { id: 'Mississippi Administrative Code', value: 'Mississippi Administrative Code' },
  { id: 'Mississippi Code Rules', value: 'Mississippi Code Rules' }],
  "Missouri": [{ id: 'Missouri Revised Statutes', value: 'Missouri Revised Statutes' },
  { id: 'Missouri Code of State Regulations', value: 'Missouri Code of State Regulations' },
  { id: 'Missouri Code Rules', value: 'Missouri Code Rules' }],
  "Montana": [{ id: 'Montana Code', value: 'Montana Code' },
  { id: 'Montana Administrative Code', value: 'Montana Administrative Code' }],
  "Nebraska": [{ id: 'Nebraska Revised Code', value: 'Nebraska Revised Code' },
  { id: 'Nebraska Administrative Code', value: 'Nebraska Administrative Code' },
  { id: 'Nebraska Code Rules', value: 'Nebraska Code Rules' }],
  "Nevada": [{ id: 'Nevada Revised Statues', value: 'Nevada Revised Statues' },
  { id: 'Nevada Administrative Code', value: 'Nevada Administrative Code' },
  { id: 'Nevada Code Rules', value: 'Nevada Code Rules' }],
  "New Hampshire": [{ id: 'New Hampshire Statues', value: 'New Hampshire Statues' },
  { id: 'New Hampshire Administrative Code', value: 'New Hampshire Administrative Code' },
  { id: 'New Hampshire Code Rules', value: 'New Hampshire Code Rules' }],
  "New Jersey": [{ id: 'New Jersey Statues', value: 'New Jersey Statues' },
  { id: 'New Jersey Administrative Code', value: 'New Jersey Administrative Code' },
  { id: 'New Jersey Rules of Court', value: 'New Jersey Code Rules of Court' }],
  "New Mexico": [{ id: 'New Mexico Statues', value: 'New Mexico Statues' },
  { id: 'New Mexico Administrative Code', value: 'New Mexico Administrative Code' },
  { id: 'New Mexico Code Rules', value: 'New Mexico Code Rules' }],
  "New York": [{ id: 'New York Consolidated Laws', value: 'New York Consolidated Laws' },
  { id: 'New York Code, Rules and Regulations', value: 'New York Code, Rules and Regulations' }],
  "North Carolina": [{ id: 'North Carolina Statues', value: 'North Carolina Statues' },
  { id: 'North Carolina Administrative Code', value: 'North Carolina Administrative Code' },
  { id: 'North Carolina Code Rules', value: 'North Carolina Code Rules' }],
  "North Dakota": [{ id: 'North Dakota Code', value: 'North Dakota Code' },
  { id: 'North Dakota Administrative Code', value: 'North Dakota Administrative Code' },
  { id: 'North Dakota Code Rules', value: 'North Dakota Code Rules' }],
  "Ohio": [{ id: 'Ohio Revised Code', value: 'Ohio Revised Code' },
  { id: 'Ohio Administrative Code', value: 'Ohio Administrative Code' },
  { id: 'Ohio Code Rules', value: 'Ohio Code Rules' }],
  "Oklahoma": [{ id: 'Oklahoma Statues', value: 'Oklahoma Statues' },
  { id: 'Oklahoma Administrative Code', value: 'Oklahoma Administrative Code' },],
  "Oregon": [{ id: 'Oregon Revised Statutes', value: 'Oregon Revised Statutes' },
  { id: 'Oregon Administrative Code', value: 'Oregon Administrative Code' },
  { id: 'Oregon Code Rules', value: 'Oregon Code Rules' }],
  "Pennsylvania": [{ id: 'Pennsylvania Statutes', value: 'Pennsylvania Statutes' },
  { id: 'Pennsylvania Code (Rules and Regulations)', value: 'Pennsylvania Code (Rules and Regulations)' },
  { id: 'Pennsylvania Local Court Rules', value: 'Pennsylvania Local Court Rules' }],
  "Puerto Rico": [{ id: ' Laws of Puerto Rico', value: ' Laws of Puerto Rico' },],
  "Rhode Island": [{ id: 'General Laws of Rhode Island', value: 'General Laws of Rhode Island' },
  { id: 'Rhode Island Administrative Code', value: 'Rhode Island Administrative Code' },
  { id: 'Rhode Island Code Rules', value: 'Rhode Island Code Rules' }],
  "South Carolina": [{ id: 'South Carolina Code', value: 'South Carolina Code' },
  { id: 'South Carolina Code of Regulations', value: 'South Carolina Code of Regulations' },
  { id: 'South Carolina Court Rules', value: ' South Carolina Court Rules' }],
  "South Dakota": [{ id: 'South Dakota Code', value: 'South Dakota Code' },
  { id: 'South Dakota Administrative Code', value: 'South Dakota Administrative Code' },],
  "Tennessee": [{ id: 'Tennessee Code', value: 'Tennessee Code' },
  { id: 'Tennessee Compilation of Rules & Regulations', value: 'Tennessee Compilation of Rules & Regulations' },
  { id: 'Tennessee Code Rules', value: 'Tennessee Code Rules' }],
  "Texas": [{ id: 'Texas Code', value: 'Texas Code' },
  { id: 'Texas Administrative Code', value: 'Texas Administrative Code' },
  { id: 'Texas Code Rules', value: 'Texas Code Rules' }],
  "Utah": [{ id: 'Utah Code', value: 'Utah Code' },
  { id: 'Utah Administrative Code', value: 'Utah Administrative Code' },
  { id: 'Utah Code Rules', value: 'Utah Code Rules' }],
  "Vermont": [{ id: 'Vermont Statutes', value: 'Vermont Statutes' },
  { id: 'Vermont Administrative Code', value: 'Vermont Administrative Code' },
  { id: 'Vermont Code Rules', value: 'Vermont Code Rules' }],
  "Virginia": [{ id: 'Virginia Code', value: 'Virginia Code' },
  { id: 'Virginia Administrative Code', value: 'Virginia Administrative Code' },
  { id: 'Virginia Code Rules', value: 'Virginia Code Rules' }],
  "Washington": [{ id: 'Washington Code', value: 'Washington Code' },
  { id: 'Washington Administrative Code', value: 'Washington Administrative Code' },
  { id: 'Washington Code Rules', value: 'Washington Code Rules' }],
  "West Virginia": [{ id: 'West Virginia Code', value: 'West Virginia Code' },
  { id: 'West Virginia Administrative Code', value: 'West Virginia Administrative Code' },
  { id: 'West Virginia Code Rules', value: 'West Virginia Code Rules' }],
  "Wisconsin": [{ id: 'Wisconsin Statues', value: 'Wisconsin Statues' },
  { id: 'Wisconsin Administrative Code', value: 'Wisconsin Administrative Code' }],
  "Wyoming": [{ id: 'Wyoming Statutes', value: 'Wyoming Statutes' },
  { id: 'Wyoming Administrative Code', value: 'Wyoming Administrative Code' },
  { id: 'Wyoming Code Rules', value: 'Wyoming Code Rules' }]
};
